// This file is auto-generated by deployMarket.ts
// It stores the contract address and match ID for other scripts to use.

export const marketAddress = "0x2B8BBaFeC74eb6dF4877c777cCbD0102653B99F6";
export const matchId = 2176811;
