// This file is auto-generated by deployMarket.ts
// It stores the contract address and match ID for other scripts to use.

export const marketAddress = "0x785ff2EF34828f51EAaF176666D23db6A9a84667";
export const matchId = 2176791;
